### ISSUE TITLE
Exponential mechanism

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#104]
Sensitivity calculations are stored in the compute_sensitivity function of aggregators. There also needs to be some utility function, which could be represented as a computation graph and passed to the runtime to execute on private data. A potential implementation-

options in the ExponentialMechanism component:
- The utility function (embedded as a graph), 
- any constants in the utility function (embedded as a release), 
- candidate_id
- output_id

In the validator:
Fill the options in the ExponentialMechanism component, which is returned when the exponential mechanism is expanded. In this way adversarial utility functions are overwritten when the node is expanded. Hardcoded utility functions are stored in the validator's aggregator files.

In the runtime:
The exponential mechanism iterates through the candidate set:
- it sets the candidate_node_id's release to the candidate
- it evaluates the graph using the same function for running the analysis graph
- it retrieves the utility from the output_node_id

Still open to suggestions on this.

**Comment by raprasad** [comment]
sync with whitepaper proofs

**Comment by raprasad** [comment]
Integrated into whitenoise-core
