### ISSUE TITLE
Rewrite README.md, write documentation indexes

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#108]
- Examples of completed README's:
   - [pytorch](https://github.com/pytorch/pytorch/blob/master/README.md)
   - [fairness 360](https://github.com/IBM/AIF360/blob/master/README.md)

---

- [x] no one cares about the Haskell and C++ implementations.  (updated by @mikephelan)
- [x] Basic explanation at the top of the README describing what the library does.
    - Link to a notebook: https://github.com/opendifferentialprivacy/whitenoise-core/blob/develop/bindings-python/notebooks/data_analysis_tutorial.ipynb
- [x] **Quickstart** + install
- [x] **Architecture** section withe brief description and potential link to a separate architecture page which describes the Validator, Runtime, Bindings, and the relationship between them
- [x] Links to **notebooks**
- [ ] Links to **white papers** as well as **existing literature**
  - See Fairness 360 for an example: https://github.com/IBM/AIF360/blob/master/README.md
- [ ] Add point of **Contact**
- [x] **List of current components**. 
   - To discuss.  Easiest way may be to have a (script generated) table for the ReadMe and a link to the Rust component docs.
- [x] The top of the lib.rs file should contain a more thorough introduction to the library (in //! header text). (updated in [CC_108_more_docs](https://github.com/opendifferentialprivacy/whitenoise-core/tree/CC_108_more_docs) by @ctcovington, but could be built out more) 
  - This is what appears here:
https://opendifferentialprivacy.github.io/whitenoise-core/doc/whitenoise_validator/index.html
  - The equivalent to this in another package is here:
https://docs.rs/ndarray/0.13.0/ndarray/
- [x] The cargo.toml also needs to be thoroughly filled out. (updated in [CC_108_more_docs](https://github.com/opendifferentialprivacy/whitenoise-core/tree/CC_108_more_docs) by @ctcovington)

**Comment by tercer** [comment]
Component list is just hard coded, sorted by category, and intended to stress most useful.  But is currently sufficient.

**Comment by raprasad** [comment]
Closing. Last items moved to #172, #173
