### ISSUE TITLE
Python bindings: lower/upper vs min/max

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#109]
We have discussed changing the terminology from _min and _max to something else-- perhaps _bounds, or maybe _lower and _upper. This is a tweak to make to this part of the code:
https://github.com/opendifferentialprivacy/whitenoise-core/blob/develop/bindings-python/whitenoise/base.py#L295-L319

While we're at it, either finish implementing RowMin and RowMax, or throw an error when only one bound is set.

**Comment by tercer** [comment]
I'd be in favor of _lowerbound _upperbound, or is that too verbose?  _lb, _ub ?

**Comment by Shoeboxam** [comment]
Should Clamp be renamed as well?
