### ISSUE TITLE
PSI Library: Implement GroupBy (Transform) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#11]
1. **OpenAPI Definition**
    - [ ] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [ ] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [ ] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by Shoeboxam** [comment]
Should GroupBy be a component, or an option on components? If it were a component, you would need to pass in a graph to be run on each group, in order to preserve the sensitivity benefits from having disjoint sets.

**Comment by raprasad** [comment]
- Replaced by #68
