### ISSUE TITLE
Consider abstracting raw datatype (i32, i64, f32 etc) via associated types

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#120]
We currently support four data types- i64, String, f64, bool- via an enum. It may be possible to adjust the enum to work on broader bit depths. The Int variant can take a class with an associated type containing the raw, specific type- i8, i16, i32, etc. One concern here is inefficiency with the extra abstraction layer, especially in the runtime- but the Value::Array float variant could contain an ArrayD<T> as an associated type, which should be a zero-cost abstraction. If handling variants via associated types is sufficiently flexible, then support for each type variant could be handled via macros.

I'm open to other ideas on supporting these types. Also keep in mind that the runtime doesn't need to support all of the data types that the validator supports.

**Comment by raprasad** [comment]
related to #114

**Comment by Shoeboxam** [comment]
This could be done via

**Comment by Shoeboxam** [comment]
I ended up aliasing the elementary types. You can configure the bit depth for most of the library, however, protobuf and noise addition still uses 64-bit ints and floats. This also doesn't provide support for casting between bit depths. If we want to support configurable bit depths for noise addition, we'll need to add some conditional compilation. Not hard, but not seemingly a priority. The vast majority of the library can be plugged with an arbitrary bit depth, which seems to be more than enough functionality at this point.
