### ISSUE TITLE
Use the "Implementation" string in component expansions

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#127]
All of the DPxxx components have a `self.implementation` string. The vision for this is that a user could switch between mechanisms and algorithms by adjusting the string. This would adjust the expansion to represent whatever algorithm you are using. For example, adjusting implementation on mean could switch between `Resize/Mean` vs `Sum/Count` vs `Bias-corrected Sum/Count`, and the various combinations of `Laplace` and `Gaussian` mechanisms. 

While these alternative combinations can be manually constructed and automatically validated by stringing the components together in the right order, adjusting string(s) would be more user friendly.

**Comment by raprasad** [comment]
- good place for new contributors to start

**Comment by mikephelan** [comment]
https://github.com/opendifferentialprivacy/whitenoise-core/tree/iss_127_mphelan

**Comment by mikephelan** [comment]
successfully pulling implementation node contents into dp_[a-z]*.rs

**Comment by mikephelan** [comment]
I am working towards conditionally injecting MechanismLaplace or MechanismGaussian based on the value of the DPMean.json property, implementation by modifying the insert of the graph node for noising. The Component constructor is being altered to have a match statement associated with the variant label.

**Comment by Shoeboxam** [comment]
The implementation string is already available in bindings, the proto, and in the dp_xxx.rs files. The implementation string also has documentation here:
https://opendifferentialprivacy.github.io/whitenoise-core/doc/whitenoise_validator/proto/struct.DpCovariance.html#structfield.implementation

You can access it via `self.implementation`.

**Comment by Shoeboxam** [comment]
Here is an example of using a value that was part of the proto struct from the validator:

https://github.com/opendifferentialprivacy/whitenoise-core/blob/develop/validator-rust/src/components/dp_covariance.rs#L70

**Comment by Shoeboxam** [comment]
Might want to think about naming here as well. I know the string is currently "implementation", but if the string adjusts the mechanism, then maybe there should be a "mechanism" string for that, and preserve the "implementation" string for alternative algorithms? Like `plug-in` vs `resize` or for histograms `stability` or `standard`?

Adding `mechanism` strings to components should be as simple as just adding their keys to the jsons.

**Comment by mikephelan** [comment]
proposed implementation at #187

**Comment by Shoeboxam** [comment]
Still need to add the plug-in mean expansion.
