### ISSUE TITLE
finish accuracy implementation

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#133]
The python bindings support it, endpoints are available in the validator, and traits are available.

Remaining:
- expand the passed component
- call into accuracy on each expanded component (or the original component) and take the first successful result
- impl Accuracy trait in the mechanism

Potential future:
- postprocess accuracy

**Comment by raprasad** [comment]
- high priority

**Comment by globusharris** [comment]
Need to add Gaussian and Geometric accuracy guarantees

**Comment by Shoeboxam** [comment]
Implementation is here: 
https://github.com/opendifferentialprivacy/whitenoise-core/pull/161
Additional traits need to be added for mechanism_simple_geometric.rs and mechanism_gaussian.rs, and then these components need to be added to the two Accuracy lists in `components/mod.rs`

**Comment by globusharris** [comment]
Sanity check:

We need to be able to get privacy bounds from accuracy bounds for the accuracy_to_privacy_usage component. 

For the geometric mechanism,

a = ceiling[(2/eps)*ln(1/alpha)].

Should I set epsilon to its minimal value, (2/a) * ln(1/alpha)? There shouldn’t be any violations if I do that right???

**Comment by globusharris** [comment]
Closed with PR #186
