### ISSUE TITLE
migrate notebooks from whitenoise-core to whitenoise-samples

### ISSUE THREAD

**Issue by tercer** [opendifferentialprivacy/whitenoise-core#142]
The notebooks demonstrating the Python bindings move to `whitenoise-samples/analysis` and get removed from this repo, along with the accompanying datasets.

**Comment by tercer** [comment]
@Shoeboxam Are you using the PUMS dataset in `/bindings-python/data` for other tests or code examples?

**Comment by Shoeboxam** [comment]
I'm currently using it, but would like to move to synthetic data.

**Comment by ctcovington** [comment]
I'd be happy to work on this if I can get a better sense from @Shoeboxam about his needs for the data.

**Comment by tercer** [comment]
We can move data to another issue.
