### ISSUE TITLE
Remove remaining Yarrow reference

### ISSUE THREAD

**Issue by tercer** [opendifferentialprivacy/whitenoise-core#146]
In my install, setup still references Yarrow:

<img width="617" alt="Screen Shot 2020-04-06 at 1 19 29 PM" src="https://user-images.githubusercontent.com/2085037/78586525-8d5de080-7809-11ea-9970-744889c60335.png">

**Comment by Shoeboxam** [comment]
Try running `pip uninstall yarrow`?

**Comment by tercer** [comment]
No luck.  Can ignore I assume?
<img width="570" alt="Screen Shot 2020-04-06 at 8 57 46 PM" src="https://user-images.githubusercontent.com/2085037/78618728-5c050500-7849-11ea-967a-04050e346eb3.png">

**Comment by raprasad** [comment]
@tercer If ^ is still an issue, see if you have a file/directories named:
   - `/bindings-python/yarrow.egg-info` 
   - `/bindings-python/yarrow` 

If so, they can be deleted.

**Comment by tercer** [comment]
@raprasad Yes that worked.
