### ISSUE TITLE
Initial Crate For Whitenoise

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#149]
- [x] Decide on version number -> **0.1.0**
- [x] Release/test initial crates prior to OpenDP and Build

---

**Comment by mikephelan** [comment]
I am able to successfully perform the dry run of the addition of our code to crates.io. However, crates.io needs every crate to be reliant only on other crates. For this reason, our architecture of having the JSON prototypes outside both the validator-rust and runtime-rust is problematic. One option is to move the prototypes directory into validator-rust and modify build.rs to stop referencing relative links outside the validator-rust crate. Another would be to create a third crate solely for the purposes of holding the prototypes, and referencing that crate from within validator-rust.

**Comment by mikephelan** [comment]
Another issue is that our package metadata value, readme, points to a relative path outside the crate. It appears that there may be a preference on the part of crate.io to have a one-to-one relationship among crates and git repositories. We may consider creating three repositories, one for runtime-rust, one for validator-rust, and one for the prototypes material. We may also consider simply copying the README.md currently found in the top-level whitenoise-core repository into every cargo crate within that git repository.

**Comment by mikephelan** [comment]
Another issue is that the runtime-rust crate references the validator via a relative path outside the crate. This can be fixed once validator-rust is a published crate, and can be directly referenced in the package metadata value, whitenoise-validator, without the relative path outside the runtime-rust crate.

**Comment by mikephelan** [comment]
Created branch of code changes which can publish successfully:
https://github.com/opendifferentialprivacy/whitenoise-core/tree/iss149_mphelan

Steps to reproduce:
(get a login key from crate.io)
cargo login <key>
rustup update
cd shitenoise-core/validator-rust
cargo publish --dry-run

**Comment by Shoeboxam** [comment]
I'm really happy to see this, thanks @mikephelan.

There is a group of packages here that sit in one repository:
https://github.com/danburkert/prost

You can see there is a top-level cargo.toml that references other packages in the workspace. From what I understand, this seems to allow them to develop on the packages without adjusting paths or uploading to cargo within the developer cycle. I'm fine with moving prototypes into the validator.

**Comment by mikephelan** [comment]
I've examined the multi-layer cargo implementation of prost and agree this is a better way to go. I'll make the modifications to my solution.

**Comment by mikephelan** [comment]
The new plan is to programmatically search for the prototypes directory via environmental variable and several other means, within the main function of build.rs in validator-rust, similar to how prost defines the location of protoc.

**Comment by mikephelan** [comment]
I've implemented the principles of the prost multi-layer cargo implementation in validator-rust, and made sympathetic changes to runtime-rust. validator-rust now locates the prototypes directory by means of an environmental variable. The target files within the prototype directory are built with the environmental variable as their base.

This solution is able to be published to crates.io successfully (in dry-run mode). We will need to determine a few things in order to merge this successfully to develop and master. We need to verify which type of license we want to use for our code base (crates.io requires that field in the Cargo.toml). We need to create a README.md for validator-rust that we can live with, as I don't think having an exact copy of the whitenoise-core README.md is really what we want to use. We will need to verify that the build is truly yielding the same results it was yielding previously, as config.compile_protos and some other areas are now working rather differently than they were previously. My testing thus far has been limited to building the project in cargo and publishing the project using crate publish (with lenient arguments turned on to dodge errors).

**Comment by mikephelan** [comment]
As per request of @raprasad at white noise stand-up on 20200421, here are the remaining tasks for pushing this crates publication issue onward to Valhalla:

- Determine a feature set and formalize it into a release branch, then reference that branch in the TOML
- Determine a license for the code, then reference that license in the TOML

nice to have:
- Update/verify documentation (to) include(s) references to the WN_PROTO_DIR environmental variable so we do not break the build experience
- resolution of #26 which would affect changes on this solution

**Comment by raprasad** [comment]
Depends on license #173

**Comment by mikephelan** [comment]
additional minor code change was necessary, see pull request #177

**Comment by mikephelan** [comment]
With initial release 0.1.0 completed
https://github.com/opendifferentialprivacy/whitenoise-core/commit/b1ec509bfc94dfc319072c8f427dcdd49965a547
we are now able to build our initial crates for WhiteNoise.
One issue is that we write to src/docs/components.rs from build.rs, which is frowned upon by the Cargo folks. They say writing to anyplace but $OUT_DIR can result in [bewildering errors](https://github.com/rust-lang/cargo/issues/5073). I imagine that writing documentation is unlikely to lead to such errors, but I thought it was worth acknowledging.
The steps for us to publish crates are ready to go. I am going to wait for acknowledgement and confirmation here, and then proceed.
```
git pull
git reset --hard
git clean -fd
git checkout b1ec509bfc94dfc319072c8f427dcdd49965a547
cargo login your-key-here
rustup update
cd whitenoise-core/validator-rust
cargo publish --dry-run
cd whitenoise-core/runtime-rust
# will fail because whitenoise-core not yet truly published
cargo publish --dry-runcargo login your-key-here
```

**Comment by raprasad** [comment]
@mikephelan This is ready to go. Will email
