### ISSUE TITLE
PSI Library: Implement Impute (Transform) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#15]
1. **Protobuff Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
first attempt in commit 6c178066e6a0a7cde21bc94e7737287302368bc2

**Comment by raprasad** [comment]
- uniform floats, uniform integers, Gaussian floats

**Comment by raprasad** [comment]
- framework is there and some testing
- need to test within a component and within the system (as other parts become ready)
