### ISSUE TITLE
Namespace issues for python and whitenoise

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#176]
(This was a known issue and overlooked in the conversion from yarrow->whitenoise)

- [x] change namespace to `opendp.whitenoise_core`, as in:
   - `import opendp.whitenoise_core`
- [ ] In the **setup.cfg file**, the `packages` value should be `opendp.whitenoise_core`
   - e.g. the **setup.py** equivalent of:
        - ` packages=['opendp.whitenoise_core'],`
- [ ] important.  The **opendp** directory should NOT have an `__init__.py` file
   - reference:  https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages
   - This allows the whitenoise-system pypi package to also use the `opendp` namespace
   - related ticket opendifferentialprivacy/whitenoise-system#189

--- 

Need to namespace with **opendp**.  Whitenoise is already in use in pypi:

```python
from opendp.whitenoise.sql import PandasReader, PrivateReader
from opendp.whitenoise.metadata import CollectionMetadata
```
source: https://github.com/opendifferentialprivacy/whitenoise-samples/blob/master/data/SQL%20Queries.ipynb

---

Example of how it is currently in the whitenoise-core notebooks and **will conflict** with the current pypi whitenoise package (that package is used for serving static files--nothing to do with our project). 
```python
import whitenoise
import whitenoise.components as op
```
source: https://github.com/opendifferentialprivacy/whitenoise-samples/blob/master/analysis/basic_data_analysis.ipynb

---

# secondary checklist

- [x] python tests
- [ ] fix sphinx doc building
- [ ] sample notebooks (may move this to a separate issue)

**Comment by raprasad** [comment]
Possible update, to verify:

- **new pypi name**: opendp-whitenoise-core
  - possible future integration to be a dependency within opendp-whitenoise
- **python usage**
    ```python
    import opendp.whitenoise_core
    import opendb.whitenoise_core.components as op   # (or similar)
    ```

**Comment by Shoeboxam** [comment]
To set the pypi name, in setup.cfg, should I switch
```
[metadata]
name = opendp
```

to 

```
[metadata]
name = opendp-whitenoise-core
```

**Comment by raprasad** [comment]
ref: https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by raprasad** [comment]
(accidental close)

**Comment by raprasad** [comment]
Fixed in whitenoise-core-python. moving notebooks to new issue
