### ISSUE TITLE
test datasets: location, size, licensing

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#179]
- Review test datasets used by whitenoise-core as well as in notebooks
- Quick checklist

---

1. Is the licensing clear?
   - No.  Is there a replacement?
1. Are they too big to be in a repository? 
   - Download utils could be used. Ask @eedeleon 
1. For smaller datasets, is a separate repo including submodule usage appropriate?
1. Communicate any questions/updates/decisions in yarrow-internals 
   - Also talk to MS, especially if a submodule is being used

**Comment by Shoeboxam** [comment]
How about we remove all test datasets from core and only use synthetic datasets? I have already done some work on this.
