### ISSUE TITLE
PSI Library: Implement Variance (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#18]
1. **Protobuff Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
first attempt in commit 4a91725150a2642f517b0dcb9f8ab09d7f22db2a

**Comment by raprasad** [comment]
- Add traits for the validator (expansions for variance and DP variance)

**Comment by raprasad** [comment]
- docs/tests moved to #62, #63
