### ISSUE TITLE
PSI Library: Implement Histogram (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#20]
1. **Protobuff Definition**
    - [x] Write definition
    - [x] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
See commit a06a67ab1db056356b7b5d5fa9f67b8e564f3829 for first attempt at the histogram runtime

**Comment by ctcovington** [comment]
We are probably not going to use the histogram code I wrote, as we might end up building the histogram out of existing components? Either way, we will probably need to generalize the `FieldEvaluation` to accept hashmaps.

**Comment by raprasad** [comment]
- Currently the returned value is a dictionary of bin names and counts.

**Comment by raprasad** [comment]
- some debugging needed on bin
- need validator traits to fully test
