### ISSUE TITLE
Typos: Dp--- and DP--- both used

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#205]
### Case mismatch?

- Note: Both of these versions are used within `validator-rust/` 
    - (except for the system-architecture.tex whitepaper)

1. DpMean/DPMean
   - **DpMean** - used in `dp_mean.rs`, `mod.rs`
   - **DPMean** - used in `DPMean.json`, `dp_mean.rs`, `components.rs`, `system-architecture.tex`
1. DPCovariance/DpCovariance
1. DPHistogram/DpHistogram
1. DPMaximum/DpMaximum

**Comment by raprasad** [comment]
> Need to call .to_camel_case() via the heck library (which prost uses) when building docs. I ran into this when building rust bindings, .....
> https://github.com/opendifferentialprivacy/whitenoise-core/blob/ms-exponential/validator-rust/build/bindings.rs#L8
> https://github.com/opendifferentialprivacy/whitenoise-core/blob/ms-exponential/validator-rust/build/bindings.rs#L77
> You just need to make the P lowercase to fix the URL, which heck will do

**Comment by Shoeboxam** [comment]
When Prost generates the proto structs, it passes the message names from the .proto file through heck's to_camel_case(). Whenever we're working with Prost-generated structs internally, the lowercase is used. The uppercase values are used for everything else.
