### ISSUE TITLE
PSI Library: Implement Count (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#21]
1. **gRPC Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
See commit 8584fa3bfc2eb2c65368c87ed14500890fa0209f for first attempt at runtime

**Comment by raprasad** [comment]
- docs/tests moved to #62, #63
