### ISSUE TITLE
PSI Library: Implement Sum (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#22]
depends on #14 

1. **gRPC Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
first attempt in commit e8a066d8c9b6a0ede651549e3db07ef2faf61eeb

**Comment by raprasad** [comment]
- need to add Traits

**Comment by raprasad** [comment]
- docs/tests moved to #62, #63
