### ISSUE TITLE
Remove runtime error message from covariances notebook

### ISSUE THREAD

**Issue by tercer** [opendifferentialprivacy/whitenoise-core#222]
A runtime error popped up in the saved version of the covariances notebook pushed to samples.  Should rerun and remove:

<img width="994" alt="Screen Shot 2020-05-06 at 12 31 19 PM" src="https://user-images.githubusercontent.com/2085037/81203575-1cd7ea00-8f96-11ea-8e27-b6d190068dcd.png">

**Comment by ctcovington** [comment]
@tercer [PR #32](https://github.com/opendifferentialprivacy/whitenoise-samples/pull/32) in `whitenoise-samples` should fix this

**Comment by ctcovington** [comment]
Closing this as it was resolved in the comment above
