### ISSUE TITLE
PSI Library: Implement Mean (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#23]
1. ** gRPC Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
first attempt in commit 1d0877fd6e0a13e85784180d6e821ee56ef7be33

**Comment by raprasad** [comment]
- needs rewriting
