### ISSUE TITLE
crates can only be used by other rust projects

### ISSUE THREAD

**Issue by FishmanL** [opendifferentialprivacy/whitenoise-core#271]
do I need to build from source to use core-python?

**Comment by Shoeboxam** [comment]
You do not need to build from source to use core-python, you can use the wheels on pypi. I'm not completely sure how to interpret this question, so I will also provide some explanation.

As of the pull-request merged today, there are now three crates- 
- validator
- runtime
- ffi

The validator and runtime crates are only directly usable from other rust projects. The ffi crate re-exports functions in the validator/runtime crates over ffi. You may access these exported functions from the compiled .dylib, .dll and .so files from any language via the C abi.

The language bindings (in R and python) include this rust repository as a submodule, and handle all of the bundling for you, for that language. So the whitenoise-core-python repository builds this core library artifact for you, and bundles it into a python package. Similarly the whitenoise-core-R repository builds this artifact for you as part of the library's source build.

**Comment by FishmanL** [comment]
The language bindings (specifically, python's) did not actually build that rust artifact/bundle it -- I needed to do that work on my own to get the library working

**Comment by FishmanL** [comment]
Actually, the issue is just that the dlls for windows are missing from the wheels
