### ISSUE TITLE
Define Metadata needed for OpenDP

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#277]
e.g. can start with: https://pypi.org/project/tworavens-preprocess/

**Comment by mikephelan** [comment]
[Proposed schema](https://github.com/privacytoolsproject/PSI-Library/blob/develop/dp-schema.json) from whitenoise core first release

**Comment by mikephelan** [comment]
For each variable, I propose we have attributes in metadata for:
name (for summary statistics and for variable types)
median
mean
mode
max
min
invalid (values)
valid (values)
stdev
unique (values)
Herfindahl index (concentration)
frequency mode
frequency midpoint
frequency fewest
mid-point
number of characters
interval (discrete or continuous)
numchar (numeric or character)
binary

This is based on PSI data release.
