### ISSUE TITLE
TheilSen and DpGumbelMedian

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#290]
1. TheilSen - a data transformation which returns an array of pairwise slopes and intercepts from the given data.
2. DpGumbelMedian - implementation of a DP median using noise sampled from a Gumbel distribution.

(created for PR #287)

**Comment by raprasad** [comment]
- [ ] update so private candidates passed to utility matched private candidates passed into the mechanism

**Comment by Shoeboxam** [comment]
For the Gumbel, make sure that effective epsilon is used. This is dependent on p, from generalized resize, and c, the c-stability. P is optional, would be nice to rebase on top of the generalized resize branch.

**Comment by Shoeboxam** [comment]
Jayshree also mentioned- we need to change the behavior dependent on the privacy definition. Essentially--
Add/Remove - omit nans/infs
Substitute - include +-inf to be clipped later
