### ISSUE TITLE
[documentation] links to github issues board broken in contributor guide

### ISSUE THREAD

**Issue by cilvento** [opendifferentialprivacy/whitenoise-core#294]
**Problem**
The links to the [issue board](https://github.com/orgs/opendifferentialprivacy/projects/1) are broken in the [contributor guide](https://github.com/opendifferentialprivacy/whitenoise-core/blob/develop/contributing.md)

**Issue Type:** Documentation

**Comment by raprasad** [comment]
@cilvento Thanks. This is fixed.  The board was marked as private and is now public.
