### ISSUE TITLE
PSI Library: Implement Impute (Statistic) (Rust)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#34]
1. **gRPC Definition**
    - [x] Write definition
    - [ ] Write comments/docs
2. **Rust Runtime**
    - [x] Write runtime
	- [ ] Implement tests
    - [ ] Write comments/docs
3. **Rust Validator**
    - [x] Write validator
	- [ ] Implement tests
    - [ ] Write comments/docs
4. **Python bindings**
    - [x] Create bindings
	- [ ] Implement tests
    - [ ] Write docs
5. **R bindings**
    - [ ] Create bindings
	- [ ] Implement tests
    - [ ] Write docs

**Comment by ctcovington** [comment]
Uniform imputation (f64 and i64) in 62dca950d9cfd3ef83e01f31193cb13c7dbe74a6
Gaussian imputation (f64) in 62dca950d9cfd3ef83e01f31193cb13c7dbe74a6

**Comment by raprasad** [comment]
- docs/tests moved to #62, #63
