### ISSUE TITLE
Add deprecation warning to https://opendp.github.io/smartnoise-core/

### ISSUE THREAD

**Issue by pdurbin** [opendifferentialprivacy/whitenoise-core#365]
smartnoise-core is deprecated in favor of the OpenDP library.

We need to update https://opendp.github.io/smartnoise-core/ to indicate this.

**Comment by pdurbin** [comment]
I added a deprecation warning in 7f86bf6.

It looks like this:

![Screen Shot 2021-10-28 at 4 29 28 PM](https://user-images.githubusercontent.com/21006/139330905-c8b9d23a-41d6-4121-a1a3-6bac6d83606b.png)

As I mentioned in my commit, I made the URL visible because you have to hover over text to know if it's clickable.

Moving this to review.

**Comment by raprasad** [comment]
completed by @pdurbin
