### ISSUE TITLE
cbindgen failing on fresh Ubuntu: index out of bounds

### ISSUE THREAD

**Issue by joshua-oss** [opendifferentialprivacy/whitenoise-core#37]
When I follow the build steps on a new install of Ubuntu, the builds for runtime-rust and validator-rust fail in the cbindgen custom build step.  I can get the build to finish and unit tests to run by commenting out the cbindgen call in both build.rs files, because the api.h in the repo is up-to-date.

The cbindgen step succeed on my previous Ubuntu laptop and my MacBook laptop, which I previously configured with all of the C++ dependencies, Conan, etc.

Here is the full backtrace for validator-rust (runtime is essentially the same):

   Compiling yarrow_validator v0.1.0 (/home/joshua/yarrow/validator-rust)
error: failed to run custom build command for `yarrow_validator v0.1.0 (/home/joshua/yarrow/validator-rust)`

Caused by:
  process didn't exit successfully: `/home/joshua/yarrow/validator-rust/target/release/build/yarrow_validator-4940303593ef9cd0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0:     0x559857ed7d98 - backtrace::backtrace::libunwind::trace::h946e3de0c90abfd7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x559857ed7d98 - backtrace::backtrace::trace_unsynchronized::h07606d21d603c43a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x559857ed7d98 - std::sys_common::backtrace::_print_fmt::h962d19ba24adc71d
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x559857ed7d98 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h19476a0c55a309e1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x559857efe64c - core::fmt::write::hace03fabe0232084
                               at src/libcore/fmt/mod.rs:1052
   5:     0x559857ed4797 - std::io::Write::write_fmt::h040dd382992db3a0
                               at src/libstd/io/mod.rs:1428
   6:     0x559857edabe5 - std::sys_common::backtrace::_print::h31d41e7ebc455053
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x559857edabe5 - std::sys_common::backtrace::print::hb9a7709d20b4b6bd
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x559857edabe5 - std::panicking::default_hook::{{closure}}::h822a6c70999551c6
                               at src/libstd/panicking.rs:204
   9:     0x559857eda926 - std::panicking::default_hook::heec975af1173ff14
                               at src/libstd/panicking.rs:224
  10:     0x559857edb2c5 - std::panicking::rust_panic_with_hook::h5af769b06ceaa2dc
                               at src/libstd/panicking.rs:474
  11:     0x559857edaddb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x559857efce81 - core::panicking::panic_fmt::hfd5708e1fe45b20b
                               at src/libcore/panicking.rs:85
  13:     0x559857efce45 - core::panicking::panic_bounds_check::h3e8ca98fc7d37627
                               at src/libcore/panicking.rs:63
  14:     0x559857c55d09 - <usize as core::slice::SliceIndex<[T]>>::index::had63db15143bff45
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/slice/mod.rs:2791
  15:     0x559857c55d09 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::h6578968298b56424
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/slice/mod.rs:2656
  16:     0x559857c55d09 - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h9e6176a6c9b0241c
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/liballoc/vec.rs:1885
  17:     0x559857c55d09 - cbindgen::bindgen::cargo::cargo::parse_dep_string::h0bfec90bee78ff23
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/cargo/cargo.rs:19
  18:     0x559857cfe031 - cbindgen::bindgen::cargo::cargo::Cargo::dependencies::{{closure}}::h868f220e9053e67a
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/cargo/cargo.rs:119
  19:     0x559857cfe031 - core::iter::adapters::map_fold::{{closure}}::h5902d8d29d965520
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/adapters/mod.rs:772
  20:     0x559857cfe031 - core::iter::traits::iterator::Iterator::fold::ok::{{closure}}::h0e73e72466d429ce
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/traits/iterator.rs:2000
  21:     0x559857cfe031 - core::iter::traits::iterator::Iterator::try_fold::h7a4edaf4a4385bfe
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/traits/iterator.rs:1876
  22:     0x559857cfe031 - core::iter::traits::iterator::Iterator::fold::h86d21a3721f2da31
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/traits/iterator.rs:2003
  23:     0x559857cfe031 - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h1678eacc7d133094
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/adapters/mod.rs:812
  24:     0x559857c7d3b4 - core::iter::traits::iterator::Iterator::for_each::h43a6585266ce6acc
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/traits/iterator.rs:659
  25:     0x559857c7d3b4 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend::h0c2b333dfd1489c6
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/liballoc/vec.rs:2056
  26:     0x559857c7d3b4 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h99caab1f43bc3030
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/liballoc/vec.rs:2036
  27:     0x559857c57396 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::hcc8f8f2a00b4d8bb
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/liballoc/vec.rs:1921
  28:     0x559857c57396 - core::iter::traits::iterator::Iterator::collect::h68117e630341fa93
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/iter/traits/iterator.rs:1658
  29:     0x559857c57396 - cbindgen::bindgen::cargo::cargo::Cargo::dependencies::he23697dc9c6c5234
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/cargo/cargo.rs:115
  30:     0x559857d3f039 - cbindgen::bindgen::parser::Parser::parse_crate::h216589f3697a9f9f
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/parser.rs:159
  31:     0x559857d3e700 - cbindgen::bindgen::parser::parse_lib::h6dd33a935187c74a
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/parser.rs:88
  32:     0x559857c44230 - cbindgen::bindgen::builder::Builder::generate::hbc0e3b4b1c19ff35
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/bindgen/builder.rs:322
  33:     0x559857bdaf3d - cbindgen::generate_with_config::h167e5409a3b9d478
                               at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.1/src/lib.rs:37
  34:     0x559857bdaf3d - build_script_build::main::hd3411c5ac314e02a
                               at /home/joshua/yarrow/validator-rust/build.rs:19
  35:     0x559857bf7393 - std::rt::lang_start::{{closure}}::h0e88d66d3bcafed9
                               at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libstd/rt.rs:67
  36:     0x559857edad03 - std::rt::lang_start_internal::{{closure}}::he3f8b3563423a3bd
                               at src/libstd/rt.rs:52
  37:     0x559857edad03 - std::panicking::try::do_call::h688c5e52f98f353d
                               at src/libstd/panicking.rs:303
  38:     0x559857ee2927 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  39:     0x559857edb769 - std::panicking::try::he72700c2f9c2c35d
                               at src/libstd/panicking.rs:281
  40:     0x559857edb769 - std::panic::catch_unwind::h71f676a40de6e61e
                               at src/libstd/panic.rs:394
  41:     0x559857edb769 - std::rt::lang_start_internal::hf18bc456048ccdad
                               at src/libstd/rt.rs:51
  42:     0x559857bdbd58 - main
  43:     0x7f6ed1705b97 - __libc_start_main
  44:     0x559857b59eba - _start
  45:                0x0 - <unknown>

**Comment by raprasad** [comment]
Closing as resolved in latest code.
