### ISSUE TITLE
sanity checks for epsilon/delta

### ISSUE THREAD

**Issue by Shoeboxam** [opendifferentialprivacy/whitenoise-core#67]
Within the validator's mechanism traits, sanity checks are needed for valid values of epsilon and delta.

**Comment by ctcovington** [comment]
Beyond the standard sanity checks (e.g. `\epsilon \geq 0`, `\delta \in [0,1]`), our current instantiation of the Gaussian Mechanism (from Dwork & Roth 14) requires that `\epsilon \in (0,1)`.

**Comment by raprasad** [comment]
PR merged
