### ISSUE TITLE
Add accuracy notebook

### ISSUE THREAD

**Issue by globusharris** [opendifferentialprivacy/whitenoise-core#89]
Add some sort of notebook that highlights how accuracy guarantees can go wrong. E.g.

- Resizing/resampling from original data
- Imputating the whole data set
- All data is outside of the clamp range

**Comment by ctcovington** [comment]
See [here](https://github.com/opendifferentialprivacy/whitenoise-samples/blob/master/analysis/accuracy_pitfalls.ipynb) -- would love for someone to look over it.

**Comment by raprasad** [comment]
In whitenoise-samples: https://github.com/opendifferentialprivacy/whitenoise-samples/blob/master/analysis/accuracy_pitfalls.ipynb

**Comment by globusharris** [comment]
I think the explanation portion is good. For the examples, I think it would be helpful to emphasize that these are diagnostic simulations, not something that someone would want to do in practice with there own data (especially when you start using large epsilon values in the second simulation).

I'm surprised at just how much the imputation of the extra 50 points messes up the accuracy guarantee, but couldn't find anything wrong with the implementation.

**Comment by saniavn** [comment]
Here is my comments:

- Variables in the second block (**age_lower_bound**, **age_upper_bound**, and **n-mise**) all have the same value as the first block. I think it is not necessary to repeat them inside the second block. 
- The print statement is long, I think it is nicer to read things without needing to scroll.
-  The accuracy value statement is too long (but I do not know how many exactly how many decimal places is enough).

**Comment by ctcovington** [comment]
Note to myself -- some of the math renders differently on github than locally and looks weird

**Comment by ctcovington** [comment]
Made some updates on the branch [here](https://github.com/opendifferentialprivacy/whitenoise-samples/blob/CC_accuracy/analysis/accuracy_pitfalls.ipynb). 

I figure that branch can be the new hub for activity on this notebook until we feel it's ready.
